version: 2

sources:
  - name: northwind
    database: curso-etl-101  
    schema: erp_northwind
    tables:
      - name: categories
      - name: customer_customer_demo
      - name: customer_demographics
      - name: customers
      - name: employee_territories
      - name: employees
      - name: order_details
      - name: orders
      - name: products
      - name: region
      - name: shippers
      - name: suppliers
      - name: territories
      - name: us_states

  - name: stripe
    tables:
      - name: payments